import { describe, it } from 'vitest';

// Phase 05 fills this in: shared accept/reject vectors for hashCanonical and the tool
// approval HMAC, executed in both Go and TypeScript over one committed fixture set.
//
// It must be bidirectional. Vectors generated by one language and checked by the same
// language prove nothing, and the two failure modes here are an auth bypass (Go accepts
// what TS would reject) and universal rejection (the reverse) — both silent.
//
// The scaffold lives here now because Phase 05 depends on this harness existing.
describe('approval crypto vectors (Phase 05)', () => {
  it.todo('hashCanonical output matches Go byte-for-byte over the shared fixtures');
  it.todo('key ordering matches Go for a non-BMP key and a U+E000..U+FFFF key in one object');
  it.todo('every accept vector verifies in both languages');
  it.todo('every reject vector fails in both languages');
  it.todo('a tampered input with a valid prior signature is rejected');
});
