import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export const FIXTURE_ROOT = new URL('../fixtures/', import.meta.url).pathname;

/**
 * Reads a fixture's raw bytes.
 *
 * Fixtures are generated by `go test ./aisdk/ -run TestConformanceFixtures
 * -update-fixtures`, so they are the exact bytes ai-go puts on the wire.
 */
export function readFixture(relPath: string): string {
  return readFileSync(join(FIXTURE_ROOT, relPath), 'utf8');
}

/**
 * Strict SSE framing check.
 *
 * The client's own parser is lenient about framing — it skips blank lines and
 * tolerates a missing terminator by simply ending when the byte stream ends. That
 * leniency hides two real server bugs: a stream that never sends `[DONE]` (which
 * happens if the terminator is tied to a `finish` chunk and the run errored instead),
 * and a frame written without the `data: ` prefix. Neither would fail the client, so
 * they are checked here instead.
 *
 * Returns the JSON payload of each frame, terminator excluded.
 */
export function parseSSEFrames(
  raw: string,
  opts: { requireDone?: boolean } = {},
): string[] {
  const { requireDone = true } = opts;

  if (raw === '') throw new Error('fixture is empty');
  if (!raw.endsWith('\n\n')) {
    throw new Error('fixture does not end with a frame terminator (\\n\\n)');
  }

  const frames = raw.slice(0, -2).split('\n\n');
  const payloads: string[] = [];
  let sawDone = false;

  frames.forEach((frame, i) => {
    if (sawDone) {
      throw new Error(`frame ${i}: content after [DONE]: ${frame}`);
    }
    if (!frame.startsWith('data: ')) {
      throw new Error(`frame ${i} is not prefixed with "data: ": ${JSON.stringify(frame)}`);
    }
    const payload = frame.slice('data: '.length);
    if (payload === '[DONE]') {
      sawDone = true;
      return;
    }
    payloads.push(payload);
  });

  if (requireDone && !sawDone) {
    throw new Error(
      'stream is missing its "data: [DONE]" terminator; the client would wait ' +
        'on a stream that has already ended',
    );
  }
  return payloads;
}

/** Frame payloads decoded as JSON, without schema validation. */
export function parseSSEChunks(raw: string, opts?: { requireDone?: boolean }): unknown[] {
  return parseSSEFrames(raw, opts).map((p, i) => {
    try {
      return JSON.parse(p);
    } catch (e) {
      throw new Error(`frame ${i} is not valid JSON: ${p}`);
    }
  });
}

/** A fixture's bytes as a ReadableStream, so the client can consume it as a response. */
export function fixtureByteStream(raw: string): ReadableStream<Uint8Array> {
  return new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(new TextEncoder().encode(raw));
      controller.close();
    },
  });
}
