package aisdk

import (
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
	"unicode/utf8"
)

// The vectors are generated by conformance/scripts/generate-crypto-vectors.mjs, in
// TypeScript, because TypeScript is the reference. Go is made to match them, and the same
// files are asserted from the TS side too — a one-directional check cannot catch the
// failure that matters, which is Go accepting what the reference would reject.

type canonicalVector struct {
	Name          string          `json:"name"`
	Note          string          `json:"note,omitempty"`
	Input         json.RawMessage `json:"input"`
	CanonicalJSON string          `json:"canonicalJSON"`
	HashCanonical string          `json:"hashCanonical"`
}

type approvalVector struct {
	Name        string          `json:"name"`
	Note        string          `json:"note,omitempty"`
	Version     string          `json:"version"`
	Secret      string          `json:"secret"`
	ApprovalID  string          `json:"approvalId"`
	ToolCallID  string          `json:"toolCallId"`
	ToolName    string          `json:"toolName"`
	Input       json.RawMessage `json:"input"`
	Signature   string          `json:"signature"`
	Expect      string          `json:"expect"`
	PrincipalID string          `json:"principalId,omitempty"`
	ChatID      string          `json:"chatId,omitempty"`
	IssuedAt    int64           `json:"iat,omitempty"`
}

func loadVectors[T any](t *testing.T, path string) []T {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate with: cd conformance && node scripts/generate-crypto-vectors.mjs)", path, err)
	}
	var out []T
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s is empty", path)
	}
	return out
}

// decodeInput turns a vector's raw JSON into the data model, which is the shape a decoded
// request body has.
func decodeInput(t *testing.T, raw json.RawMessage) any {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("decode input: %v", err)
	}
	return v
}

// vectorsGoCannotReproduce are the two cases where Go's JSON decoder has already
// destroyed the input before any of our code runs: an unpaired surrogate escape becomes
// U+FFFD on ingest (measured), so Go never sees the value TypeScript canonicalized.
//
// This is a genuine, documented divergence rather than a bug to paper over. The
// substitution is lossy in a way that matters for a hash: "\uD800" and "\uD801" both
// become U+FFFD, so two distinct inputs would produce one digest. Go therefore refuses to
// canonicalize invalid UTF-8 instead of hashing a collapsed value.
var vectorsGoCannotReproduce = map[string]string{
	"lone-surrogate-key":   "Go's json.Unmarshal replaces the lone surrogate with U+FFFD on ingest",
	"lone-surrogate-value": "Go's json.Unmarshal replaces the lone surrogate with U+FFFD on ingest",
}

func TestCanonicalVectors_MatchTypeScript(t *testing.T) {
	vecs := loadVectors[canonicalVector](t, "testdata/canonical-vectors.json")

	var checked int
	for _, v := range vecs {
		t.Run(v.Name, func(t *testing.T) {
			if why, skip := vectorsGoCannotReproduce[v.Name]; skip {
				t.Skipf("documented divergence: %s", why)
			}

			input := decodeInput(t, v.Input)

			got, err := CanonicalJSON(input)
			if err != nil {
				t.Fatalf("CanonicalJSON: %v", err)
			}
			if got != v.CanonicalJSON {
				t.Errorf("canonicalJSON mismatch\n go: %s\n ts: %s", got, v.CanonicalJSON)
			}

			gotHash, err := HashCanonical(input)
			if err != nil {
				t.Fatalf("HashCanonical: %v", err)
			}
			if gotHash != v.HashCanonical {
				t.Errorf("hashCanonical mismatch\n go: %s\n ts: %s", gotHash, v.HashCanonical)
			}
			checked++
		})
	}
	if checked == 0 {
		t.Fatal("no canonical vectors were actually checked")
	}
}

// The vector that detects the sort divergence. Guarded explicitly so it cannot be
// removed or renamed without a failure: an emoji paired with a Latin-1 key agrees in both
// languages, so a fixture set without a non-BMP/U+E000-class pair would ship the bug.
func TestCanonicalVectors_SortDivergenceVectorIsPresent(t *testing.T) {
	vecs := loadVectors[canonicalVector](t, "testdata/canonical-vectors.json")

	var found bool
	for _, v := range vecs {
		if v.Name != "nonbmp-key-vs-private-use-key" {
			continue
		}
		found = true
		// UTF-16 order puts U+1F600 (first code unit 0xD83D) before U+E000; UTF-8 byte
		// order puts U+E000 (0xEE...) before U+1F600 (0xF0...). The expectation must
		// encode the former.
		iEmoji := strings.Index(v.CanonicalJSON, "\U0001F600")
		iPrivate := strings.Index(v.CanonicalJSON, "")
		if iEmoji < 0 || iPrivate < 0 {
			t.Fatalf("vector lost one of its keys: %s", v.CanonicalJSON)
		}
		if iEmoji > iPrivate {
			t.Errorf("expectation is in byte order, not UTF-16 order — it would pass "+
				"with sort.Strings and therefore detect nothing: %s", v.CanonicalJSON)
		}
	}
	if !found {
		t.Fatal("the non-BMP vs private-use-key vector is missing; without it the " +
			"key-sort divergence is untested")
	}
}

func TestApprovalVectors_MatchTypeScript(t *testing.T) {
	vecs := loadVectors[approvalVector](t, "testdata/approval-vectors.json")

	var accepts, rejects int
	for _, v := range vecs {
		t.Run(v.Name, func(t *testing.T) {
			binding := ApprovalBinding{
				ApprovalID:  v.ApprovalID,
				ToolCallID:  v.ToolCallID,
				ToolName:    v.ToolName,
				Input:       decodeInput(t, v.Input),
				PrincipalID: v.PrincipalID,
				ChatID:      v.ChatID,
				IssuedAt:    v.IssuedAt,
			}

			got := VerifyToolApproval([]byte(v.Secret), v.Signature, binding)
			want := v.Expect == "accept"
			if got != want {
				t.Errorf("verify = %v, want %v (%s)\n  note: %s", got, want, v.Expect, v.Note)
			}
			if want {
				accepts++
			} else {
				rejects++
			}
		})
	}

	// A vector file that drifted to all-accept or all-reject would still pass every
	// individual case while testing nothing.
	if accepts == 0 || rejects == 0 {
		t.Errorf("vectors must exercise both outcomes: %d accept, %d reject", accepts, rejects)
	}
}

// Signing must reproduce the reference signature, not merely verify it. A Go server whose
// signatures a TypeScript verifier rejects is just as broken as the reverse.
func TestSignToolApprovalV1_ReproducesTypeScriptSignature(t *testing.T) {
	vecs := loadVectors[approvalVector](t, "testdata/approval-vectors.json")

	var checked int
	for _, v := range vecs {
		if v.Version != "v1" || v.Expect != "accept" {
			continue
		}
		// Only the vectors whose signature is the canonical one for their binding; the
		// padded and standard-base64 variants are re-encodings of it.
		if strings.ContainsAny(v.Signature, "+/=") {
			continue
		}
		t.Run(v.Name, func(t *testing.T) {
			got, err := SignToolApprovalV1([]byte(v.Secret), ApprovalBinding{
				ApprovalID: v.ApprovalID, ToolCallID: v.ToolCallID,
				ToolName: v.ToolName, Input: decodeInput(t, v.Input),
			})
			if err != nil {
				t.Fatalf("SignToolApprovalV1: %v", err)
			}
			if got != v.Signature {
				t.Errorf("signature mismatch\n go: %s\n ts: %s", got, v.Signature)
			}
			checked++
		})
	}
	if checked == 0 {
		t.Fatal("no v1 signing vectors were checked")
	}
}

func TestSignToolApprovalV2_ReproducesVectorSignature(t *testing.T) {
	vecs := loadVectors[approvalVector](t, "testdata/approval-vectors.json")

	var checked int
	for _, v := range vecs {
		if v.Version != "v2" || v.Expect != "accept" {
			continue
		}
		t.Run(v.Name, func(t *testing.T) {
			got, err := SignToolApprovalV2([]byte(v.Secret), ApprovalBinding{
				ApprovalID: v.ApprovalID, ToolCallID: v.ToolCallID, ToolName: v.ToolName,
				Input: decodeInput(t, v.Input), PrincipalID: v.PrincipalID,
				ChatID: v.ChatID, IssuedAt: v.IssuedAt,
			})
			if err != nil {
				t.Fatalf("SignToolApprovalV2: %v", err)
			}
			if got != v.Signature {
				t.Errorf("signature mismatch\n go: %s\n ts: %s", got, v.Signature)
			}
			checked++
		})
	}
	if checked == 0 {
		t.Fatal("no v2 signing vectors were checked")
	}
}

// --- properties and traps not expressible as a single vector ---

// The depth budget must trip BEFORE hashing, since this is the first code to touch
// attacker JSON on the approval path.
func TestHashCanonical_RejectsPastDepthBudget(t *testing.T) {
	deep := any(1)
	for i := 0; i < CanonicalJSONMaxDepth+5; i++ {
		deep = map[string]any{"a": deep}
	}
	if _, err := HashCanonical(deep); err == nil {
		t.Fatal("deeply nested input was hashed instead of rejected")
	} else if !errors.Is(err, ErrCanonicalJSON) {
		t.Errorf("err = %v, want ErrCanonicalJSON", err)
	}

	// At the budget it must still succeed, or the limit is off by one and legitimate
	// payloads break.
	ok := any(1)
	for i := 0; i < CanonicalJSONMaxDepth-1; i++ {
		ok = map[string]any{"a": ok}
	}
	if _, err := HashCanonical(ok); err != nil {
		t.Errorf("input at the depth budget was rejected: %v", err)
	}
}

func TestCanonicalJSON_RejectsInvalidUTF8(t *testing.T) {
	// A WTF-8 encoded lone surrogate: what JSON.stringify emits verbatim and Go would
	// silently turn into U+FFFD.
	bad := string([]byte{0xED, 0xA0, 0x80})
	if utf8.ValidString(bad) {
		t.Fatal("test fixture is valid UTF-8; it cannot exercise the guard")
	}

	for _, tc := range []struct {
		name  string
		input any
	}{
		{"in a value", map[string]any{"k": bad}},
		{"in a key", map[string]any{bad: 1}},
		{"bare string", bad},
		{"inside an array", []any{bad}},
	} {
		if _, err := CanonicalJSON(tc.input); err == nil {
			t.Errorf("%s: invalid UTF-8 was canonicalized instead of rejected", tc.name)
		} else if !errors.Is(err, ErrCanonicalJSON) {
			t.Errorf("%s: err = %v, want ErrCanonicalJSON", tc.name, err)
		}
	}
}

// Two maps with the same entries in different insertion order must canonicalize
// identically — the whole point of the canonical form.
func TestCanonicalJSON_InsertionOrderIndependent(t *testing.T) {
	keys := []string{"z", "a", "m", "Ａ", "\U0001F600", "", "é", "0"}

	var first string
	for shift := range keys {
		obj := map[string]any{}
		for i := range keys {
			obj[keys[(i+shift)%len(keys)]] = i
		}
		got, err := CanonicalJSON(obj)
		if err != nil {
			t.Fatalf("CanonicalJSON: %v", err)
		}
		if shift == 0 {
			first = got
			continue
		}
		// Values differ per rotation, so compare the key sequence only.
		if gotKeys, wantKeys := extractKeys(got), extractKeys(first); gotKeys != wantKeys {
			t.Errorf("key order changed with insertion order\n got: %s\nwant: %s",
				gotKeys, wantKeys)
		}
	}
}

func extractKeys(canonical string) string {
	var keys []string
	for _, part := range strings.Split(strings.Trim(canonical, "{}"), ",") {
		if i := strings.LastIndex(part, ":"); i > 0 {
			keys = append(keys, part[:i])
		}
	}
	return strings.Join(keys, "|")
}

// Numbers must not depend on the Go type the caller happened to use.
func TestHashCanonical_NumericTypesAgree(t *testing.T) {
	want, err := HashCanonical(map[string]any{"n": float64(42)})
	if err != nil {
		t.Fatal(err)
	}
	for _, v := range []any{int(42), int64(42), float32(42), json.Number("42")} {
		got, err := HashCanonical(map[string]any{"n": v})
		if err != nil {
			t.Fatalf("%T: %v", v, err)
		}
		if got != want {
			t.Errorf("%T(42) hashed differently from float64(42): %s vs %s", v, got, want)
		}
	}
}

func TestDecodeBase64URLTolerant_MatchesReferenceLeniency(t *testing.T) {
	// The reference maps -→+ and _→/ then calls atob, which accepts padding, the
	// standard alphabet, and an unpadded final group.
	cases := []struct {
		in string
		ok bool
	}{
		{"AAAA", true},
		{"AAA=", true},  // padding — base64.RawURLEncoding would reject
		{"AA==", true},  // more padding
		{"a-_b", true},  // url alphabet
		{"a+/b", true},  // standard alphabet — RawURLEncoding would reject
		{"AAA", true},   // unpadded final group
		{"!!!!", false}, // invalid alphabet
		{"", false},     // empty
		{"====", false}, // padding only
	}
	for _, tc := range cases {
		_, ok := DecodeBase64URLTolerant(tc.in)
		if ok != tc.ok {
			t.Errorf("DecodeBase64URLTolerant(%q) ok = %v, want %v", tc.in, ok, tc.ok)
		}
	}
}

func TestVerifyToolApproval_NeverPanicsOnHostileSignature(t *testing.T) {
	b := ApprovalBinding{ApprovalID: "a", ToolCallID: "c", ToolName: "t", Input: nil}
	for _, sig := range []string{
		"", "=", "====", "!!!", strings.Repeat("A", 10000),
		"\x00\x01", "AAAA", "-_-_", "\n", " ",
	} {
		if VerifyToolApproval([]byte("secret"), sig, b) {
			t.Errorf("hostile signature %q verified", sig)
		}
	}
}

func TestCheckToolApproval_ErrorOrdering(t *testing.T) {
	secret := []byte("s3cret")
	b := ApprovalBinding{ApprovalID: "a1", ToolCallID: "c1", ToolName: "del", Input: nil}
	good, err := SignToolApprovalV2(secret, b)
	if err != nil {
		t.Fatal(err)
	}

	// A configured secret with no signature is reported as missing, distinctly from
	// invalid — the reference distinguishes them and so do audit logs.
	err = CheckToolApproval(secret, "", b)
	var sigErr *InvalidToolApprovalSignatureError
	if !errors.As(err, &sigErr) {
		t.Fatalf("missing signature: err = %v, want InvalidToolApprovalSignatureError", err)
	}
	if sigErr.Reason != ApprovalReasonMissingSignature {
		t.Errorf("reason = %q, want %q", sigErr.Reason, ApprovalReasonMissingSignature)
	}

	if err := CheckToolApproval(secret, "AAAA", b); !errors.As(err, &sigErr) ||
		sigErr.Reason != ApprovalReasonInvalidSignature {
		t.Errorf("bad signature: err = %v, want reason %q", err, ApprovalReasonInvalidSignature)
	}

	if err := CheckToolApproval(secret, good, b); err != nil {
		t.Errorf("valid signature rejected: %v", err)
	}

	// No secret means verification is off, matching the reference. Documented as a risk,
	// not a feature.
	if err := CheckToolApproval(nil, "", b); err != nil {
		t.Errorf("unconfigured secret should skip verification, got %v", err)
	}
}

// The error must not echo the attacker-supplied signature into a log.
func TestInvalidToolApprovalSignatureError_DoesNotEchoSignature(t *testing.T) {
	secret := []byte("s")
	hostile := "AAAA-hostile-marker-AAAA"
	err := CheckToolApproval(secret, hostile,
		ApprovalBinding{ApprovalID: "a1", ToolCallID: "c1", ToolName: "t"})
	if err == nil {
		t.Fatal("expected rejection")
	}
	if strings.Contains(err.Error(), "hostile-marker") {
		t.Errorf("error echoes the supplied signature: %v", err)
	}
}

// The legacy newline payload the reference still accepts must NOT verify here.
func TestVerifyToolApproval_RejectsLegacyNewlinePayload(t *testing.T) {
	vecs := loadVectors[approvalVector](t, "testdata/approval-vectors.json")
	var found bool
	for _, v := range vecs {
		if v.Name != "v1-legacy-newline-payload-must-not-verify" {
			continue
		}
		found = true
		if VerifyToolApproval([]byte(v.Secret), v.Signature, ApprovalBinding{
			ApprovalID: v.ApprovalID, ToolCallID: v.ToolCallID, ToolName: v.ToolName,
			Input: decodeInput(t, v.Input),
		}) {
			t.Error("a legacy newline-joined signature verified; ai-go deliberately " +
				"does not implement that fallback")
		}
	}
	if !found {
		t.Fatal("the legacy-newline vector is missing")
	}
}
